# Generated by Django 5.1.7 on 2025-03-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '블로그', 'verbose_name_plural': '블로그 목록'},
        ),
    ]
