# Generated by Django 5.1.7 on 2025-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('travel', '여행'), ('ect', '기타'), ('pet', '반려동물'), ('anniversary', '기념일')], default='ect', max_length=20, verbose_name='카테고리'),
        ),
    ]
